-- Idempotent raw-log classification migration.
--
-- Fresh sinks run this after 01-log-sink.sql and before the completed-catalog
-- assertion. Existing Arc-B sinks run the same file explicitly while the
-- log-ingester is stopped, then run 02-log-sink-assertion.sql before bringing
-- the writer back. ADD COLUMN backfills every retained row inside the same
-- transaction; IF NOT EXISTS makes a verified second run a no-op.
--
-- A stored generated column keeps classification at the write boundary
-- without adding a function or view. It is appended after every legacy column
-- so fresh and upgraded sinks have the same attnum order.

\set ON_ERROR_STOP on

BEGIN;

-- Do not wait indefinitely behind an unexpectedly active writer. Operators
-- stop log-ingester first; a busy sink fails cleanly and can be retried.
SET LOCAL lock_timeout = '10s';

ALTER TABLE public.funnel_access_log
  ADD COLUMN IF NOT EXISTS status_class TEXT
  GENERATED ALWAYS AS (
    CASE
      WHEN status BETWEEN 100 AND 199 THEN '1xx'
      WHEN status BETWEEN 200 AND 299 THEN '2xx'
      WHEN status BETWEEN 300 AND 399 THEN '3xx'
      WHEN status BETWEEN 400 AND 499 THEN '4xx'
      WHEN status BETWEEN 500 AND 599 THEN '5xx'
      ELSE 'other'
    END
  ) STORED;

COMMENT ON COLUMN public.funnel_access_log.status_class IS
  'Stored HTTP status bucket used by the Funnel rollup; generated by the sink schema contract.';

-- IF NOT EXISTS must not bless a pre-existing ordinary column. Expression
-- behavior is pinned by the completed-catalog assertion and boundary smokes.
DO $$
DECLARE
  generation_kind "char";
  column_type     regtype;
BEGIN
  SELECT a.attgenerated, a.atttypid::regtype
    INTO generation_kind, column_type
  FROM pg_attribute a
  WHERE a.attrelid = 'public.funnel_access_log'::regclass
    AND a.attname = 'status_class'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  IF generation_kind IS DISTINCT FROM 's' OR column_type IS DISTINCT FROM 'text'::regtype THEN
    RAISE EXCEPTION
      'log sink: status_class must be a stored generated text column (generation %, type %)',
      coalesce(generation_kind::text, '<missing>'),
      coalesce(column_type::text, '<missing>');
  END IF;
END;
$$ LANGUAGE plpgsql;

COMMIT;
