-- Native, rotatable access tokens for the non-OIDC authentication door.
--
-- Plaintext tokens are generated by the operator CLI and never cross this
-- boundary. The database stores only a SHA-256 digest, a public lookup prefix,
-- a bounded attribution label, and lifecycle timestamps.
--
-- This file is idempotent for both fresh init and an existing deployment. Run
-- db/03-grants-assertion.sql after it so the completed privilege catalog is
-- verified before the new server starts.

-- Existing databases predate the dedicated administrator. Create a NOLOGIN
-- role so this migration can land safely before its password is provisioned.
-- Fresh compose init creates the same role as LOGIN when
-- OPENBRAIN_TOKEN_ADMIN_PASSWORD is set in db/00-roles.sh.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'openbrain_token_admin') THEN
    CREATE ROLE openbrain_token_admin NOLOGIN NOSUPERUSER NOCREATEDB
      NOCREATEROLE NOREPLICATION NOBYPASSRLS;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Preserve the intentional LOGIN/NOLOGIN state while converging every
-- cluster-level privilege flag on existing databases. The upgrade helper
-- separately provisions LOGIN and its password when the operator opts in.
ALTER ROLE openbrain_token_admin WITH NOSUPERUSER NOCREATEDB NOCREATEROLE
  NOREPLICATION NOBYPASSRLS;

CREATE SCHEMA IF NOT EXISTS native_auth;
REVOKE ALL ON SCHEMA native_auth FROM PUBLIC;

CREATE TABLE IF NOT EXISTS native_auth.access_token (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  prefix      TEXT NOT NULL UNIQUE,
  token_hash  BYTEA NOT NULL UNIQUE,
  label       TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at  TIMESTAMPTZ,
  CONSTRAINT access_token_prefix_shape CHECK (
    prefix ~ '^ob1_[A-Za-z0-9_-]{8}$'
  ),
  CONSTRAINT access_token_hash_shape CHECK (octet_length(token_hash) = 32),
  CONSTRAINT access_token_revocation_order CHECK (
    revoked_at IS NULL OR revoked_at >= created_at
  )
);

-- PostgreSQL char_length and JavaScript code-point iteration now share the
-- same 1-128 definition. Use JavaScript's complete trim-character set rather
-- than btrim's default ASCII space, and remove an explicit C0/C1 code-point
-- set from consideration so behavior is independent of locale character
-- classes. PostgreSQL text cannot contain U+0000, so the set starts at U+0001.
-- Drop/re-add converges preview or existing databases that applied an earlier
-- version of this idempotent migration.
ALTER TABLE native_auth.access_token
  DROP CONSTRAINT IF EXISTS access_token_label_shape,
  ADD CONSTRAINT access_token_label_shape CHECK (
    char_length(label) BETWEEN 1 AND 128
    AND label = btrim(
      label,
      U&'\0009\000A\000B\000C\000D\0020\00A0\1680\2000\2001\2002\2003\2004\2005\2006\2007\2008\2009\200A\2028\2029\202F\205F\3000\FEFF'
    )
    AND label = translate(
      label,
      U&'\0001\0002\0003\0004\0005\0006\0007\0008\0009\000A\000B\000C\000D\000E\000F' ||
      U&'\0010\0011\0012\0013\0014\0015\0016\0017\0018\0019\001A\001B\001C\001D\001E\001F' ||
      U&'\007F\0080\0081\0082\0083\0084\0085\0086\0087\0088\0089\008A\008B\008C\008D\008E\008F' ||
      U&'\0090\0091\0092\0093\0094\0095\0096\0097\0098\0099\009A\009B\009C\009D\009E\009F',
      ''
    )
  );

-- The CLI generates the secret and digest, then calls this function with only
-- the non-recoverable hash. SECURITY DEFINER keeps INSERT away from the login
-- role and fixes the search path against object-shadowing attacks.
CREATE OR REPLACE FUNCTION native_auth.register_access_token(
  requested_prefix TEXT,
  requested_hash BYTEA,
  requested_label TEXT
)
RETURNS TABLE (
  id BIGINT,
  prefix TEXT,
  label TEXT,
  created_at TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, native_auth
AS $function$
  INSERT INTO native_auth.access_token (prefix, token_hash, label)
  VALUES (requested_prefix, requested_hash, requested_label)
  RETURNING access_token.id, access_token.prefix, access_token.label,
            access_token.created_at;
$function$;

-- Revocation is one-way: only active rows match, and the caller cannot supply
-- a timestamp or mutate another column. A repeated revoke returns no row.
CREATE OR REPLACE FUNCTION native_auth.revoke_access_token(
  requested_prefix TEXT
)
RETURNS TABLE (
  id BIGINT,
  prefix TEXT,
  label TEXT,
  created_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, native_auth
AS $function$
  UPDATE native_auth.access_token
  SET revoked_at = GREATEST(clock_timestamp(), access_token.created_at)
  WHERE access_token.prefix = requested_prefix
    AND access_token.revoked_at IS NULL
  RETURNING access_token.id, access_token.prefix, access_token.label,
            access_token.created_at, access_token.revoked_at;
$function$;

-- PostgreSQL grants function execution to PUBLIC by default. Tear that down
-- on every reapply before assigning the two reviewed routines to the dedicated
-- operator role.
REVOKE ALL ON FUNCTION native_auth.register_access_token(TEXT, BYTEA, TEXT)
  FROM PUBLIC;
REVOKE ALL ON FUNCTION native_auth.revoke_access_token(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION native_auth.register_access_token(TEXT, BYTEA, TEXT)
  FROM openbrain_app, openbrain_token_admin, openbrain_readonly;
REVOKE ALL ON FUNCTION native_auth.revoke_access_token(TEXT)
  FROM openbrain_app, openbrain_token_admin, openbrain_readonly;

-- Start from a known privilege state on reapply. The runtime may read only;
-- the administrator may list non-secret columns and call the two lifecycle
-- functions; the trusted backup identity must be able to dump table/sequence
-- state. Neither role receives broad schema-default privileges.
REVOKE ALL ON native_auth.access_token FROM PUBLIC;
REVOKE ALL ON native_auth.access_token FROM openbrain_app;
REVOKE ALL ON native_auth.access_token FROM openbrain_token_admin;
REVOKE ALL ON native_auth.access_token FROM openbrain_readonly;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA native_auth FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA native_auth FROM openbrain_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA native_auth FROM openbrain_token_admin;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA native_auth FROM openbrain_readonly;
REVOKE ALL ON SCHEMA native_auth
  FROM openbrain_app, openbrain_token_admin, openbrain_readonly;

GRANT USAGE ON SCHEMA native_auth TO openbrain_app;
GRANT SELECT (prefix, token_hash, label, revoked_at)
  ON native_auth.access_token TO openbrain_app;

GRANT USAGE ON SCHEMA native_auth TO openbrain_token_admin;
GRANT SELECT (id, prefix, label, created_at, revoked_at)
  ON native_auth.access_token TO openbrain_token_admin;
GRANT EXECUTE ON FUNCTION
  native_auth.register_access_token(TEXT, BYTEA, TEXT)
  TO openbrain_token_admin;
GRANT EXECUTE ON FUNCTION native_auth.revoke_access_token(TEXT)
  TO openbrain_token_admin;

GRANT USAGE ON SCHEMA native_auth TO openbrain_readonly;
GRANT SELECT ON native_auth.access_token TO openbrain_readonly;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA native_auth TO openbrain_readonly;
